"""Extract reviewed catalogue samples; never execute scripts or contact source websites."""
import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SAMPLES = [
    ("search-only", "14741_2c26091c31e95c3e3478dc90b6d473ed.json", 0, False, False, []),
    ("categories-only", "71e56d4f.json", 7, False, True, []),
    ("discovery-and-categories", "71e56d4f.json", 5, True, True, ["最近更新", "总排行榜", "完本排行"]),
    ("rankings-are-tags-too", "4dc410d1.json", 11, True, True, ["周榜", "月榜", "总榜"]),
    ("grouped-and-unnamed", "71e56d4f.json", 18, True, True,
     ["重磅推荐", "推荐 · 男生必读", "推荐 · 女生爱看", "小编推荐"]),
    ("lenient-mixed", "14741_2c26091c31e95c3e3478dc90b6d473ed.json", 189, True, True,
     ["我的收藏", "-------- 排行榜 -------- · 完结高分", "-------- 排行榜 -------- · 新晋作者", "月排行榜", "季排行榜", "半年排行"]),
    ("dynamic-catalog", "71e56d4f.json", 12, True, True, None),
]


def extract(directory):
    inventory = json.loads((ROOT / "source-compatibility/discovery-routing-inventory.json").read_text(encoding="utf-8"))
    files = {}
    for entry in inventory["files"]:
        raw = (directory / entry["file"]).read_bytes()
        if hashlib.sha256(raw).hexdigest() != entry["sha256"]:
            raise ValueError(f"Input changed: {entry['file']}")
        files[entry["file"]] = (entry["sha256"], json.loads(raw.decode("utf-8-sig")))
    samples = []
    for key, filename, index, feed, categories, titles in SAMPLES:
        digest, sources = files[filename]
        source = sources[index]
        fields = {key: source[key] for key in ("enabledExplore", "exploreUrl", "exploreScreen", "homepageModules") if key in source}
        samples.append({
            "id": key, "name": source["bookSourceName"],
            "provenance": {"kind": "desktop-catalog", "file": filename, "sha256": digest, "index": index},
            "hasSearch": bool(source.get("searchUrl", "").strip()), "fields": fields,
            "expected": {"hasFeed": feed, "hasCategories": categories, "feedTitles": titles,
                         "resolution": "dynamic" if titles is None else "static"},
        })
    samples.append({
        "id": "discovery-only", "name": "仅显式首页（补充契约样本）",
        "provenance": {"kind": "synthetic", "reason": "No independent homepageModules in the seven desktop files."},
        "hasSearch": True,
        "fields": {"homepageModules": json.dumps([
            {"key": "recent", "type": "card", "title": "最近更新", "url": "/search?page={{page}}"}
        ], ensure_ascii=False, separators=(",", ":"))},
        "expected": {"hasFeed": True, "hasCategories": False, "feedTitles": ["最近更新"], "resolution": "static"},
    })
    return {"scope": "Catalogue fields are unchanged. No headers, accounts, response bodies or book content. "
                     "Dynamic samples verify provisional capabilities only; synthetic cases are labelled. "
                     "Expected routing is manually reviewed, not generated by the classifier.", "samples": samples}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("directory", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.write_text(json.dumps(extract(args.directory), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
